cmake_minimum_required(VERSION 3.15)
set(DEMO_OUTPUT_SUBDIR "build/plot-rotating-triangle")
include("${CMAKE_CURRENT_LIST_DIR}/../snes_demo_helpers.cmake")

message(STATUS "Compiling the rotating checkerboard and comparing both assembly paths")
build_gsu_payload("${CMAKE_CURRENT_LIST_DIR}/triangle.dc")
build_snes_host("${CMAKE_CURRENT_LIST_DIR}" rotating-triangle)
build_snes_host("${CMAKE_CURRENT_LIST_DIR}" rotating-triangle-negative -D FORCE_BAD_RESULT=1)

if(VERIFY_MESEN)
    # A failed run must not inherit captured phases from an earlier rotation.
    foreach(phase RANGE 0 63)
        if(phase LESS 10)
            set(phase "0${phase}")
        endif()
        file(REMOVE "${OUTPUT_DIR}/rotating-frame-${phase}.png")
    endforeach()
    file(REMOVE "${OUTPUT_DIR}/rotating-negative-preview.png" "${OUTPUT_DIR}/rotating-failure.png")
    set(mesen_options --testrunner --timeout=120 --doNotSaveSettings
        --snes.disableFrameSkipping=true --debug.scriptWindow.allowIoOsAccess=true)
    foreach(suffix IN ITEMS "" "-negative")
        file(REMOVE "${OUTPUT_DIR}/rotating-triangle${suffix}-verification.log")
        run_command("${MESEN}" ${mesen_options}
            "${CMAKE_CURRENT_LIST_DIR}/verify${suffix}.lua"
            "${OUTPUT_DIR}/rotating-triangle${suffix}.sfc")
        if(NOT EXISTS "${OUTPUT_DIR}/rotating-triangle${suffix}-verification.log")
            message(FATAL_ERROR "Mesen produced no verification evidence for the rotating triangle${suffix}")
        endif()
        file(READ "${OUTPUT_DIR}/rotating-triangle${suffix}-verification.log" evidence)
        if(suffix STREQUAL "")
            set(expected "^PASS rotating triangle: 64 poses plus phase wrap,")
        else()
            set(expected "^PASS rotating triangle negative:")
        endif()
        if(NOT evidence MATCHES "${expected}")
            message(FATAL_ERROR "Mesen verification failed: ${evidence}")
        endif()
        string(STRIP "${evidence}" evidence)
        message(STATUS "${evidence}")
    endforeach()
    foreach(phase RANGE 0 63)
        if(phase LESS 10)
            set(phase "0${phase}")
        endif()
        if(NOT EXISTS "${OUTPUT_DIR}/rotating-frame-${phase}.png")
            message(FATAL_ERROR "Missing captured rotation phase ${phase}")
        endif()
    endforeach()
    if(NOT EXISTS "${OUTPUT_DIR}/rotating-negative-preview.png")
        message(FATAL_ERROR "Mesen produced no screenshot for the deliberate failure path")
    endif()
endif()
message(STATUS "Open ${OUTPUT_DIR}/rotating-triangle.sfc to see the checkerboard rotating")
