cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED OPTIMIZATION)
    set(OPTIMIZATION 2)
endif()
if(NOT OPTIMIZATION MATCHES "^[2s]$")
    message(FATAL_ERROR "This RAM/OBJ host requires OPTIMIZATION=2 or s; O0/O1 exceed the shared bank's code reservation")
endif()
set(DEMO_OUTPUT_SUBDIR "build/interactive-shapes")
include("${CMAKE_CURRENT_LIST_DIR}/../snes_demo_helpers.cmake")
build_gsu_payload("${CMAKE_CURRENT_LIST_DIR}/main.dc" "${CMAKE_CURRENT_LIST_DIR}/discoc.toml")
configure_file("${OUTPUT_DIR}/triangle.bin" "${OUTPUT_DIR}/interactive-shapes.bin" COPYONLY)
configure_file("${OUTPUT_DIR}/triangle.s" "${OUTPUT_DIR}/interactive-shapes.s" COPYONLY)
file(SIZE "${OUTPUT_DIR}/triangle.bin" payload_size)
if(payload_size GREATER 24576)
    message(FATAL_ERROR "Payload exceeds the code reservation $70:8000..DFFF")
endif()
file(READ "${OUTPUT_DIR}/triangle.s" assembly)
if(NOT assembly MATCHES "__DISCO_BITMAP_SCBR[ \t]+\\$00" OR
   NOT assembly MATCHES "__DISCO_BITMAP_SCMR[ \t]+\\$25" OR
   NOT assembly MATCHES "__DISCO_CODE_START_ADDRESS[ \t]+\\$708000")
    message(FATAL_ERROR "Host requires OBJ/4bpp/base0 and code at $70:8000")
endif()
build_snes_host("${CMAKE_CURRENT_LIST_DIR}" interactive-shapes)
build_snes_host("${CMAKE_CURRENT_LIST_DIR}" interactive-shapes-negative -D FORCE_BAD_RESULT=1)
if(BENCHMARK)
    if(NOT VERIFY_MESEN)
        require_program(MESEN Mesen)
    endif()
    build_snes_host("${CMAKE_CURRENT_LIST_DIR}" interactive-shapes-benchmark -D CONTINUOUS_RENDER=1)
    string(REGEX MATCH "(ibt|iwt) r6, #\\$0+ [^\n]+\n    stop ; CODE\\+\\$([0-9A-F]+)" stop_match "${assembly}")
    if(NOT stop_match)
        message(FATAL_ERROR "Missing normal main STOP")
    endif()
    math(EXPR stop_address "0x708000 + 0x${CMAKE_MATCH_2}" OUTPUT_FORMAT HEXADECIMAL)
    file(WRITE "${OUTPUT_DIR}/benchmark-config.lua" "return {stop=${stop_address},bytes=${payload_size}}\n")
    file(REMOVE "${OUTPUT_DIR}/benchmark.json" "${OUTPUT_DIR}/benchmark-error.log")
    run_command("${MESEN}" --testrunner --timeout=120 --doNotSaveSettings
        --snes.region=Ntsc --snes.gsuClockSpeed=100 --snes.enableRandomPowerOnState=false
        --snes.disableFrameSkipping=true --debug.scriptWindow.allowIoOsAccess=true
        "${CMAKE_CURRENT_LIST_DIR}/benchmark.lua" "${OUTPUT_DIR}/interactive-shapes-benchmark.sfc")
    if(NOT EXISTS "${OUTPUT_DIR}/benchmark.json" OR EXISTS "${OUTPUT_DIR}/benchmark-error.log")
        message(FATAL_ERROR "Missing/failed GSU benchmark evidence")
    endif()
endif()
if(VERIFY_MESEN)
    foreach(i RANGE 1 512)
        if(i LESS 10)
            set(number "00${i}")
        elseif(i LESS 100)
            set(number "0${i}")
        else()
            set(number "${i}")
        endif()
        file(REMOVE "${OUTPUT_DIR}/interactive-frame-${number}.bmp")
    endforeach()
    foreach(size RANGE 6 16)
        file(REMOVE "${OUTPUT_DIR}/interactive-wire-${size}.bmp" "${OUTPUT_DIR}/interactive-filled-${size}.bmp")
    endforeach()
    foreach(suffix IN ITEMS "" "-negative")
        file(REMOVE "${OUTPUT_DIR}/interactive-shapes${suffix}-verification.log")
        if(suffix STREQUAL "")
            set(script verify.lua)
        else()
            set(script verify-negative.lua)
        endif()
        run_command("${MESEN}" --testrunner --timeout=120 --doNotSaveSettings
            --snes.region=Ntsc --snes.gsuClockSpeed=100 --snes.enableRandomPowerOnState=false
            --snes.ppuExtraScanlinesBeforeNmi=0 --snes.ppuExtraScanlinesAfterNmi=0
            --snes.disableFrameSkipping=true --debug.scriptWindow.allowIoOsAccess=true
            "${CMAKE_CURRENT_LIST_DIR}/${script}" "${OUTPUT_DIR}/interactive-shapes${suffix}.sfc")
        if(NOT EXISTS "${OUTPUT_DIR}/interactive-shapes${suffix}-verification.log")
            message(FATAL_ERROR "Mesen produced no verification evidence")
        endif()
        file(READ "${OUTPUT_DIR}/interactive-shapes${suffix}-verification.log" evidence)
        if(NOT evidence MATCHES "^PASS interactive shapes")
            message(FATAL_ERROR "${evidence}")
        endif()
        message(STATUS "${evidence}")
    endforeach()
endif()
message(STATUS "ROM: ${OUTPUT_DIR}/interactive-shapes.sfc (${payload_size}-byte GSU payload)")
