cmake_minimum_required(VERSION 3.15)
if(NOT DEFINED ROOT_DIR)
    get_filename_component(ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

file(STRINGS "${ROOT_DIR}/cmake/build-sources.txt" manifest_lines REGEX "^disco_")
set(expected)
foreach(line IN LISTS manifest_lines)
    string(REGEX MATCH "^disco_[A-Za-z0-9_]+" target "${line}")
    list(APPEND expected "${target}")
endforeach()
if(NOT expected)
    message(FATAL_ERROR "No test targets found in the source manifest")
endif()
list(SORT expected)

function(check_targets label text)
    string(REGEX MATCHALL "disco_[A-Za-z0-9_]+" actual "${text}")
    list(REMOVE_DUPLICATES actual)
    list(SORT actual)
    if(NOT actual STREQUAL expected)
        set(missing ${expected})
        set(unexpected ${actual})
        foreach(target IN LISTS actual)
            list(REMOVE_ITEM missing "${target}")
        endforeach()
        foreach(target IN LISTS expected)
            list(REMOVE_ITEM unexpected "${target}")
        endforeach()
        message(FATAL_ERROR "${label} test targets differ from cmake/build-sources.txt. Missing: [${missing}]. Unexpected: [${unexpected}].")
    endif()
endfunction()

# Read the actual target arrays, not comments mentioning an unbuilt target.
file(READ "${ROOT_DIR}/build.sh" shell_helper)
string(REGEX REPLACE "#[^\r\n]*" "" shell_helper "${shell_helper}")
string(REGEX MATCH "targets\\+=\\([^)]*\\)" shell_targets "${shell_helper}")
check_targets("build.sh --test" "${shell_targets}")

file(READ "${ROOT_DIR}/build.ps1" powershell_helper)
string(REGEX REPLACE "#[^\r\n]*" "" powershell_helper "${powershell_helper}")
string(REGEX MATCH "\\$targets[ \t\r\n]*\\+=[ \t\r\n]*@\\([^)]*\\)" powershell_targets "${powershell_helper}")
check_targets("build.ps1 -Test" "${powershell_targets}")

file(READ "${ROOT_DIR}/tests/run_prebuilt_tests.cmake" runner)
string(REGEX REPLACE "#[^\r\n]*" "" runner "${runner}")
string(REGEX MATCH "foreach\\(test IN ITEMS [^)]*\\)" unit_targets "${runner}")
string(REGEX MATCHALL "\\$\\{BIN_DIR\\}/disco_[A-Za-z0-9_]+" explicit_targets "${runner}")
check_targets("run_prebuilt_tests.cmake" "${unit_targets};${explicit_targets}")
message(STATUS "Direct build helpers, source manifest and prebuilt test runner agree")
