cmake_minimum_required(VERSION 3.15)
if(NOT DEFINED TEST_DIR)
    message(FATAL_ERROR "TEST_DIR is required")
endif()
set(root "${TEST_DIR}/target-parity-fixture")
file(MAKE_DIRECTORY "${root}/cmake" "${root}/tests")
file(WRITE "${root}/cmake/build-sources.txt"
    "disco_unit_tests tests/Unit.cpp\ndisco_gsu_execution_tests tests/Execution.cpp\ndisco_gsu_benchmarks benchmarks/Runner.cpp\n")
set(shell [=[targets+=(disco_unit_tests disco_gsu_execution_tests disco_gsu_benchmarks)
]=])
set(powershell [=[$targets += @('disco_unit_tests', 'disco_gsu_execution_tests', 'disco_gsu_benchmarks')
]=])
set(runner [=[foreach(test IN ITEMS disco_unit_tests)
endforeach()
run_checked("${BIN_DIR}/disco_gsu_execution_tests${EXE_SUFFIX}" --self-test)
run_checked("${BIN_DIR}/disco_gsu_benchmarks${EXE_SUFFIX}" --self-test)
]=])
function(reset_fixture)
    file(WRITE "${root}/build.sh" "${shell}")
    file(WRITE "${root}/build.ps1" "${powershell}")
    file(WRITE "${root}/tests/run_prebuilt_tests.cmake" "${runner}")
endfunction()
function(expect_result expected_result expected_message)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DROOT_DIR=${root}"
        -P "${CMAKE_CURRENT_LIST_DIR}/BuildTargetParity.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected_result STREQUAL "pass")
        if(NOT result STREQUAL "0")
            message(FATAL_ERROR "Valid target lists failed: ${output}${error}")
        endif()
    elseif(result STREQUAL "0" OR NOT "${output}${error}" MATCHES "${expected_message}")
        message(FATAL_ERROR "Invalid target list did not produce ${expected_message}: ${result}; ${output}${error}")
    endif()
endfunction()
reset_fixture()
expect_result(pass "")

file(WRITE "${root}/build.sh" [=[targets+=(
    # disco_unit_tests
    disco_gsu_execution_tests disco_gsu_benchmarks)
]=])
expect_result(fail "build.sh --test.*Missing:.*disco_unit_tests")
reset_fixture()
file(WRITE "${root}/build.ps1" [=[$targets += @(
    # 'disco_unit_tests',
    'disco_gsu_execution_tests', 'disco_gsu_benchmarks')
]=])
expect_result(fail "build.ps1 -Test.*Missing:.*disco_unit_tests")
reset_fixture()
string(REPLACE "run_checked(\"\${BIN_DIR}/disco_gsu_benchmarks" "# run_checked(\"\${BIN_DIR}/disco_gsu_benchmarks" commented_runner "${runner}")
file(WRITE "${root}/tests/run_prebuilt_tests.cmake" "${commented_runner}")
expect_result(fail "run_prebuilt_tests.cmake.*Missing:.*disco_gsu_benchmarks")
reset_fixture()
file(WRITE "${root}/build.sh" "targets+=(disco_unit_tests disco_gsu_execution_tests disco_gsu_benchmarks disco_unexpected_tests)\n")
expect_result(fail "build.sh --test.*Unexpected:.*disco_unexpected_tests")
reset_fixture()
message(STATUS "Build-target parity positive and negative checks passed")
