set(link --origin 0x706000 --init-runtime --ram-bank 0 --stack-pointer 0x2000)
foreach(level IN ITEMS 0 1)
    run_command("${DISCC}" "-O${level}" "${ROOT_DIR}/tests/fixtures/gsu_local_optimization.dc" -o "${TEST_DIR}/locals-${level}.o")
    run_command("${DISCLD}" "${TEST_DIR}/locals-${level}.o" ${link} -o "${TEST_DIR}/locals-${level}.bin")
    run_command("${GSU_RUNNER}" "${TEST_DIR}/locals-${level}.bin" 0x706000
        --ram-byte 0x700100 11 --reads 0x700100 1 --word 0x700102 22
        --word 0x700104 18 --word 0x700106 11 --word 0x700108 81 --word 0x70010a 13
        --word 0x70010c 4 --word 0x70010e 26 --register 0 42 --register 6 0)
endforeach()

# Each result is computed from a volatile seed, not a constant. Exercise every
# shift count, both signednesses, high-byte paths and all sixteen bit positions.
set(shifts "")
foreach(shift RANGE 0 15)
    math(EXPR address "0x200 + ${shift} * 8")
    math(EXPR right_address "${address} + 2")
    math(EXPR signed_address "${address} + 4")
    math(EXPR bit_address "${address} + 6")
    math(EXPR mask "1 << ${shift}")
    string(APPEND shifts "*(unsigned word*)${address} = bits << (unsigned word)(byte)${shift};\n"
        "*(unsigned word*)${right_address} = bits >> (unsigned word)(byte)${shift};\n"
        "*(word*)${signed_address} = value >> (word)(byte)${shift};\n"
        "*(unsigned word*)${bit_address} = (bits & (unsigned word)${mask}) >> (unsigned word)(byte)${shift};\n")
endforeach()
file(WRITE "${TEST_DIR}/shifts.dc" "word main() {\nword value = *(volatile word*)0x100;\nunsigned word bits = (unsigned word)value;\n${shifts}\n*(word*)0x300 = ((value ^ 1) & 512) >> (word)(byte)9;\n*(word*)0x302 = (value >> 15) & 1;\n*(word*)0x304 = (value & (word)32768) >> 15;\nreturn 42;\n}\n")
foreach(level IN ITEMS 0 1)
    run_command("${DISCC}" "-O${level}" "${TEST_DIR}/shifts.dc" -o "${TEST_DIR}/shifts-${level}.o")
    run_command("${DISCC}" "-O${level}" --emit-asm "${TEST_DIR}/shifts.dc" -o "${TEST_DIR}/shifts-${level}.s")
    run_command("${DISCAS}" "${TEST_DIR}/shifts-${level}.s" -o "${TEST_DIR}/shifts-${level}-asm.o")
    foreach(suffix IN ITEMS "" "-asm")
        run_command("${DISCLD}" "${TEST_DIR}/shifts-${level}${suffix}.o" ${link}
            --emit-asm "${TEST_DIR}/shifts-${level}${suffix}-final.s" -o "${TEST_DIR}/shifts-${level}${suffix}.bin")
    endforeach()
    file(SHA256 "${TEST_DIR}/shifts-${level}.bin" direct)
    file(SHA256 "${TEST_DIR}/shifts-${level}-asm.bin" assembled)
    if(NOT direct STREQUAL assembled)
        message(FATAL_ERROR "Specialized shift compiler assembly differs from direct codegen")
    endif()
    foreach(seed IN ITEMS 0 1 127 128 255 512 32767 32768 65535)
        math(EXPR low "${seed} & 255")
        math(EXPR high "${seed} >> 8")
        if(seed GREATER_EQUAL 32768)
            math(EXPR signed_seed "${seed} - 65536")
        else()
            set(signed_seed ${seed})
        endif()
        set(expect --ram-byte 0x700100 ${low} --ram-byte 0x700101 ${high} --reads 0x700100 1)
        foreach(shift RANGE 0 15)
            math(EXPR address "0x700200 + ${shift} * 8")
            math(EXPR left "(${seed} << ${shift}) & 65535")
            math(EXPR right "${seed} >> ${shift}")
            math(EXPR signed_right "(${signed_seed} >> ${shift}) & 65535")
            math(EXPR bit "(${seed} >> ${shift}) & 1")
            list(APPEND expect --word ${address} ${left})
            math(EXPR address "${address} + 2")
            list(APPEND expect --word ${address} ${right})
            math(EXPR address "${address} + 2")
            list(APPEND expect --word ${address} ${signed_right})
            math(EXPR address "${address} + 2")
            list(APPEND expect --word ${address} ${bit})
        endforeach()
        math(EXPR checker "(${seed} >> 9) & 1")
        math(EXPR top_bit "${seed} >> 15")
        math(EXPR sign_mask "${top_bit} * 65535")
        run_command("${GSU_RUNNER}" "${TEST_DIR}/shifts-${level}.bin" 0x706000 ${expect}
            --word 0x700300 ${checker} --word 0x700302 ${top_bit} --word 0x700304 ${sign_mask}
            --register 0 42 --register 6 0)
    endforeach()
endforeach()
file(READ "${TEST_DIR}/shifts-1-final.s" assembly)
if(NOT assembly MATCHES "hib" OR NOT assembly MATCHES "swap")
    message(FATAL_ERROR "O1 did not select high-byte/packing shift instructions")
endif()

# Runtime-invalid shifts/division must still fail-stop after forwarding folds
# a local initializer. The optimizer must not erase their check as dead code.
foreach(expression IN ITEMS "x << count" "x / count" "x % count")
    if(expression MATCHES "<<")
        set(counts -1 16)
        set(fault 5)
    else()
        set(counts 0)
        set(fault 6)
    endif()
    foreach(count IN LISTS counts)
        file(WRITE "${TEST_DIR}/fault.dc" "word main() { word x = *(volatile word*)0x100; word count = ${count}; word ignored = ${expression}; return 42; }")
        foreach(level IN ITEMS 0 1)
            run_command("${DISCC}" "-O${level}" "${TEST_DIR}/fault.dc" -o "${TEST_DIR}/fault.o")
            run_command("${DISCLD}" "${TEST_DIR}/fault.o" ${link} -o "${TEST_DIR}/fault.bin")
            run_command("${GSU_RUNNER}" "${TEST_DIR}/fault.bin" 0x706000 --ram-byte 0x700100 9 --register 6 ${fault})
        endforeach()
    endforeach()
endforeach()
