set(source "${ROOT_DIR}/tests/fixtures/gsu_contributor_correctness.dc")
run_command("${DISCC}" "${source}" -o "${TEST_DIR}/correctness.o")
run_command("${DISCC}" --emit-asm "${source}" -o "${TEST_DIR}/correctness.s")
run_command("${DISCAS}" "${TEST_DIR}/correctness.s" -o "${TEST_DIR}/correctness-asm.o")

foreach(origin IN ITEMS 0x008000 0x706000)
    foreach(suffix IN ITEMS "" "-asm")
        set(payload "${TEST_DIR}/correctness-${origin}${suffix}")
        run_command("${DISCLD}" "${TEST_DIR}/correctness${suffix}.o" --origin ${origin}
            --init-runtime --ram-bank 0 --stack-pointer 0x2000 --emit-asm "${payload}-final.s" -o "${payload}.bin")
        run_command("${DISCAS}" "${payload}-final.s" -o "${payload}-final.o")
        run_command("${DISCLD}" "${payload}-final.o" -o "${payload}-final.bin")
        file(SHA256 "${payload}.bin" expected_hash)
        file(SHA256 "${payload}-final.bin" final_hash)
        if(NOT expected_hash STREQUAL final_hash)
            message(FATAL_ERROR "Contributor reconciliation changed bytes in linked assembly (${origin}${suffix})")
        endif()
        foreach(seed IN ITEMS 0 1 2 3 126 127 128 129 254 255 256 32766 32767 32768 32769 65534 65535)
            math(EXPR low "${seed} & 255")
            math(EXPR high "${seed} >> 8")
            set(signed_word 50)
            set(unsigned_word 50)
            set(signed_byte 50)
            set(unsigned_byte 50)
            if(seed EQUAL 32768)
                set(signed_word 10)
                set(unsigned_word 30)
            elseif(seed EQUAL 65535)
                set(signed_word 20)
                set(unsigned_word 40)
            elseif(seed EQUAL 0)
                set(signed_word 30)
                set(unsigned_word 10)
            elseif(seed EQUAL 32767)
                set(signed_word 40)
                set(unsigned_word 20)
            endif()
            if(low EQUAL 128)
                set(signed_byte 10)
                set(unsigned_byte 30)
            elseif(low EQUAL 255)
                set(signed_byte 20)
                set(unsigned_byte 40)
            elseif(low EQUAL 0)
                set(signed_byte 30)
                set(unsigned_byte 10)
            elseif(low EQUAL 127)
                set(signed_byte 40)
                set(unsigned_byte 20)
            endif()

            # Independent source-level oracle: simultaneous swaps, 16-bit wrap,
            # and a mutated fallthrough predecessor joining direct dispatch.
            math(EXPR total "(${seed} + 1) & 65535")
            foreach(selector IN ITEMS 1 2)
                math(EXPR a "(${seed} + ${selector}) & 65535")
                math(EXPR b "(${a} + 1) & 65535")
                if(selector EQUAL 1)
                    math(EXPR a "(${a} + 5) & 65535")
                endif()
                foreach(iteration RANGE 1 3)
                    set(previous_a ${a})
                    math(EXPR a "(${b} + 3) & 65535")
                    set(b ${previous_a})
                endforeach()
                math(EXPR total "(${total} + (${a} + 1) * 2 + ${b}) & 65535")
            endforeach()
            math(EXPR odd "${seed} & 1")
            if(odd)
                math(EXPR fallback "(${seed} + 7) & 65535")
            else()
                math(EXPR fallback "(${seed} - 3) & 65535")
            endif()
            math(EXPR swapped "(${seed} + 1) & 65535")
            math(EXPR iterations "${seed} & 3")
            run_command("${GSU_RUNNER}" "${payload}.bin" ${origin}
                --screen-mode 0 --screen-base 32
                --ram-byte 0x700100 ${low} --ram-byte 0x700101 ${high} --reads 0x700100 1
                --word 0x700120 22 --word 0x700122 22
                --word 0x700124 ${signed_word} --word 0x700126 ${unsigned_word}
                --word 0x700128 ${signed_byte} --word 0x70012a ${unsigned_byte}
                --word 0x70012c ${total} --word 0x70012e ${fallback}
                --word 0x700130 ${swapped} --word 0x700132 ${seed}
                --word 0x700134 26 --word 0x700136 20
                --writes 0x700150 0 --writes 0x700152 ${iterations}
                --plots 0 16 --rpix 0 1 --register 0 42 --register 6 0 --register 10 0x1ffc)
        endforeach()
    endforeach()
    file(SHA256 "${TEST_DIR}/correctness-${origin}.bin" direct_hash)
    file(SHA256 "${TEST_DIR}/correctness-${origin}-asm.bin" assembly_hash)
    if(NOT direct_hash STREQUAL assembly_hash)
        message(FATAL_ERROR "Contributor reconciliation compiler assembly differs from the direct backend (${origin})")
    endif()
endforeach()

if(OPTIMIZATION MATCHES "^[2s]$")
    execute_process(COMMAND "${DISCC}" "-O${OPTIMIZATION}" --emit-ir "${source}"
        RESULT_VARIABLE status OUTPUT_VARIABLE ir ERROR_VARIABLE error)
    if(NOT status STREQUAL "0" OR NOT ir MATCHES "phi" OR NOT ir MATCHES "hardware_loop.end" OR
       NOT ir MATCHES "call @returning_loop" OR ir MATCHES "const 999([^0-9]|$)")
        message(FATAL_ERROR "Reconciliation must exercise live PHIs, hardware backedges, switch calls and unreachable pruning:\n${error}\n${ir}")
    endif()
endif()
