set(link --origin 0x008000 --init-runtime --ram-bank 0 --stack-pointer 0x2000)
foreach(level IN ITEMS 0 1 2)
    run_command("${DISCC}" -O${level} "${ROOT_DIR}/tests/fixtures/gsu_sccp.dc" -o "${TEST_DIR}/sccp-${level}.o")
    run_command("${DISCC}" -O${level} --emit-asm "${ROOT_DIR}/tests/fixtures/gsu_sccp.dc" -o "${TEST_DIR}/sccp-${level}.s")
    run_command("${DISCAS}" "${TEST_DIR}/sccp-${level}.s" -o "${TEST_DIR}/sccp-${level}-asm.o")
    foreach(suffix IN ITEMS "" "-asm")
        run_command("${DISCLD}" "${TEST_DIR}/sccp-${level}${suffix}.o" ${link} --emit-asm "${TEST_DIR}/sccp-${level}${suffix}-final.s" -o "${TEST_DIR}/sccp-${level}${suffix}.bin")
        run_command("${DISCAS}" "${TEST_DIR}/sccp-${level}${suffix}-final.s" -o "${TEST_DIR}/sccp-${level}${suffix}-final.o")
        run_command("${DISCLD}" "${TEST_DIR}/sccp-${level}${suffix}-final.o" -o "${TEST_DIR}/sccp-${level}${suffix}-final.bin")
        file(SHA256 "${TEST_DIR}/sccp-${level}${suffix}.bin" expected)
        file(SHA256 "${TEST_DIR}/sccp-${level}${suffix}-final.bin" actual)
        if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "O${level} SCCP linked assembly did not round-trip byte for byte")
        endif()
        foreach(seed IN ITEMS 0 1 127 128 255 32767 32768 65535)
            math(EXPR low "${seed} & 255")
            math(EXPR high "${seed} >> 8")
            if(seed EQUAL 0)
                set(varying 19)
            else()
                set(varying 11)
            endif()
            run_command("${GSU_RUNNER}" "${TEST_DIR}/sccp-${level}${suffix}.bin" 0x008000
                --screen-mode 0 --screen-base 16 --ram-byte 0x700100 ${low} --ram-byte 0x700101 ${high}
                --reads 0x700100 1 --reads 0x700102 0 --writes 0x700150 1
                --word 0x700150 3 --word 0x700120 42 --word 0x700122 42 --word 0x700124 ${varying}
                --word 0x700126 32768 --word 0x700128 65535 --word 0x70012a 1 --word 0x70012c 18
                --word 0x70012e 3 --word 0x700130 1 --plots 0 2 --color 0 1 --rpix 0 2
                --register 0 42 --register 6 0 --register 10 0x1ffc)
        endforeach()
    endforeach()
    file(SHA256 "${TEST_DIR}/sccp-${level}.bin" direct)
    file(SHA256 "${TEST_DIR}/sccp-${level}-asm.bin" assembled)
    if(NOT direct STREQUAL assembled)
        message(FATAL_ERROR "O${level} SCCP compiler assembly did not match the direct backend")
    endif()
endforeach()
execute_process(COMMAND "${DISCC}" -O2 --emit-ir "${ROOT_DIR}/tests/fixtures/gsu_sccp.dc"
    RESULT_VARIABLE ir_status OUTPUT_VARIABLE ir ERROR_VARIABLE ir_errors)
if(NOT ir_status STREQUAL "0" OR ir MATCHES "switch " OR ir MATCHES "const 999([^0-9]|$)")
    message(FATAL_ERROR "SCCP failed to prune provably dead dispatch/effects: ${ir_errors}\n${ir}")
endif()
if(NOT ir MATCHES "phi" OR NOT ir MATCHES "condbr" OR NOT ir MATCHES "hardware_loop\\.end")
    message(FATAL_ERROR "SCCP fixture no longer exercises surviving PHIs, unknown branches and hardware backedges")
endif()

# Faults discovered through PHIs retain their original effect ordering. The
# first observable store executes; the following store must remain unreachable.
foreach(operation IN ITEMS division remainder shift)
    if(operation STREQUAL "shift")
        set(value 16)
        set(expression "1 << divisor")
        set(fault 5)
    else()
        set(value 0)
        set(fault 6)
        if(operation STREQUAL "division")
            set(expression "42 / divisor")
        else()
            set(expression "42 % divisor")
        endif()
    endif()
    file(WRITE "${TEST_DIR}/${operation}.dc"
        "word main() { word seed=*(volatile word*)0x100; word divisor; if(seed) divisor=${value}; else divisor=${value}; *(volatile word*)0x120=7; word result=${expression}; *(volatile word*)0x122=9; return result; }")
    foreach(level IN ITEMS 0 1 2)
        set(OPTIMIZATION ${level})
        check_round_trip("${operation}-${level}" "${TEST_DIR}/${operation}.dc" ${link})
        foreach(suffix IN ITEMS "" "-asm")
            foreach(seed IN ITEMS 0 1)
                run_command("${GSU_RUNNER}" "${TEST_DIR}/${operation}-${level}${suffix}.bin" 0x008000
                    --ram-byte 0x700100 ${seed} --word 0x700120 7 --word 0x700122 0
                    --writes 0x700120 1 --writes 0x700122 0 --register 6 ${fault})
            endforeach()
        endforeach()
    endforeach()
endforeach()
unset(OPTIMIZATION)
