string(REGEX REPLACE "^language_conformance_" "" category "${CASE}")
file(GLOB sources "${ROOT_DIR}/tests/language/${category}/*.dc")
list(SORT sources)
if(NOT sources)
    message(FATAL_ERROR "Empty conformance category: ${category}")
endif()
foreach(source IN LISTS sources)
    file(READ "${source}" content)
    set(expected "")
    if(content MATCHES "// error: ([^\n]+)")
        set(expected "${CMAKE_MATCH_1}")
    endif()
    foreach(target IN ITEMS gsu spc700)
        if(content MATCHES "// target: gsu" AND target STREQUAL "spc700")
            continue()
        endif()
        set(diagnostic "${expected}")
        if(target STREQUAL "spc700" AND content MATCHES "// spc-error: ([^\n]+)")
            set(diagnostic "${CMAKE_MATCH_1}")
        endif()
        execute_process(COMMAND "${DISCC}" --check --target "${target}" "${source}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
        if(diagnostic)
            if(result STREQUAL "0" OR NOT error MATCHES "${diagnostic}" OR error MATCHES "IR verifier:")
                message(FATAL_ERROR "Invalid conformance input did not produce its language diagnostic (${target}): ${source}\n${output}\n${error}")
            endif()
        elseif(NOT result STREQUAL "0")
            message(FATAL_ERROR "Valid conformance input failed (${target}): ${source}\n${output}\n${error}")
        endif()
    endforeach()
endforeach()
