set(link --origin 0x706000 --init-runtime --ram-bank 0 --stack-pointer 0x2000)
foreach(level IN ITEMS 0 1)
    run_command("${DISCC}" "-O${level}" "${ROOT_DIR}/tests/fixtures/gsu_selection_optimization.dc" -o "${TEST_DIR}/selection-${level}.o")
    run_command("${DISCLD}" "${TEST_DIR}/selection-${level}.o" ${link} --emit-asm "${TEST_DIR}/selection-${level}-final.s" -o "${TEST_DIR}/selection-${level}.bin")
    run_command("${GSU_RUNNER}" "${TEST_DIR}/selection-${level}.bin" 0x706000
        --ram-byte 0x700100 11 --reads 0x700100 1 --word 0x700102 60
        --word 0x700104 32 --word 0x700106 65521 --word 0x700108 65520
        --word 0x70010a 4 --word 0x70010c 92 --word 0x70010e 4 --register 0 42 --register 6 0)
endforeach()
file(READ "${TEST_DIR}/selection-1-final.s" assembly)
if(NOT assembly MATCHES "to r[578][^\n]*\n    from r[578]")
    message(FATAL_ERROR "O1 did not select direct allocated ALU destinations")
endif()

# Dynamic seed, every representable power-of-two factor/divisor, both signs
# and both signednesses. Expectations use independent 64-bit host arithmetic.
set(operations "")
foreach(shift RANGE 0 15)
    math(EXPR power "1 << ${shift}")
    math(EXPR negative "-${power}")
    if(shift EQUAL 15)
        set(signed_divisor -32768)
    else()
        set(signed_divisor ${power})
    endif()
    math(EXPR base "0x400 + ${shift} * 18")
    set(expressions "value * (word)${power}" "value * (word)${negative}"
        "(word)${power} * value" "value / (word)${signed_divisor}" "value % (word)${signed_divisor}"
        "value / (word)${negative}" "value % (word)${negative}"
        "bits / (unsigned word)${power}" "bits % (unsigned word)${power}")
    set(index 0)
    foreach(expression IN LISTS expressions)
        math(EXPR address "${base} + ${index} * 2")
        string(APPEND operations "*(unsigned word*)${address} = (unsigned word)(${expression});\n")
        math(EXPR index "${index} + 1")
    endforeach()
endforeach()
file(WRITE "${TEST_DIR}/powers.dc" "word main() {\nword value = *(volatile word*)0x100;\nunsigned word bits = (unsigned word)value;\n${operations}\nreturn 42;\n}\n")
foreach(level IN ITEMS 0 1)
    run_command("${DISCC}" "-O${level}" "${TEST_DIR}/powers.dc" -o "${TEST_DIR}/powers-${level}.o")
    run_command("${DISCC}" "-O${level}" --emit-asm "${TEST_DIR}/powers.dc" -o "${TEST_DIR}/powers-${level}.s")
    run_command("${DISCAS}" "${TEST_DIR}/powers-${level}.s" -o "${TEST_DIR}/powers-${level}-asm.o")
    foreach(suffix IN ITEMS "" "-asm")
        run_command("${DISCLD}" "${TEST_DIR}/powers-${level}${suffix}.o" ${link}
            --emit-asm "${TEST_DIR}/powers-${level}${suffix}-final.s" -o "${TEST_DIR}/powers-${level}${suffix}.bin")
    endforeach()
    file(SHA256 "${TEST_DIR}/powers-${level}.bin" direct)
    file(SHA256 "${TEST_DIR}/powers-${level}-asm.bin" assembled)
    if(NOT direct STREQUAL assembled)
        message(FATAL_ERROR "Constant arithmetic assembly differs from direct codegen")
    endif()
    run_command("${DISCAS}" "${TEST_DIR}/powers-${level}-final.s" -o "${TEST_DIR}/powers-final-${level}.o")
    run_command("${DISCLD}" "${TEST_DIR}/powers-final-${level}.o" -o "${TEST_DIR}/powers-final-${level}.bin")
    file(SHA256 "${TEST_DIR}/powers-final-${level}.bin" final)
    if(NOT direct STREQUAL final)
        message(FATAL_ERROR "Final arithmetic assembly does not round-trip byte for byte")
    endif()
    foreach(seed IN ITEMS 0 1 3 7 127 128 255 512 32767 32768 32769 65529 65535)
        math(EXPR low "${seed} & 255")
        math(EXPR high "${seed} >> 8")
        if(seed GREATER_EQUAL 32768)
            math(EXPR value "${seed} - 65536")
        else()
            set(value ${seed})
        endif()
        set(expect --ram-byte 0x700100 ${low} --ram-byte 0x700101 ${high} --reads 0x700100 1)
        foreach(shift RANGE 0 15)
            math(EXPR power "1 << ${shift}")
            math(EXPR negative "-${power}")
            if(shift EQUAL 15)
                set(divisor -32768)
            else()
                set(divisor ${power})
            endif()
            math(EXPR base "0x700400 + ${shift} * 18")
            set(index 0)
            foreach(expression IN ITEMS "${value} * ${power}" "${value} * ${negative}" "${value} * ${power}"
                    "${value} / ${divisor}" "${value} % ${divisor}" "${value} / ${negative}" "${value} % ${negative}"
                    "${seed} / ${power}" "${seed} % ${power}")
                math(EXPR expected "(${expression}) & 65535")
                math(EXPR address "${base} + ${index} * 2")
                list(APPEND expect --word ${address} ${expected})
                math(EXPR index "${index} + 1")
            endforeach()
        endforeach()
        run_command("${GSU_RUNNER}" "${TEST_DIR}/powers-${level}.bin" 0x706000 ${expect} --register 0 42 --register 6 0)
    endforeach()
endforeach()

# A leaf using specialized / and % must not overwrite R1/R2 while plotting.
file(WRITE "${TEST_DIR}/plot-powers.dc" "word main() { word value = *(volatile word*)0x100; plot { at (17, 23); word q = value / 8; word r = value % -8; *(word*)0x102 = q; *(word*)0x104 = r; *(word*)0x106 = cursor.x; *(word*)0x108 = cursor.y; } return 42; }")
foreach(level IN ITEMS 0 1)
    run_command("${DISCC}" "-O${level}" "${TEST_DIR}/plot-powers.dc" -o "${TEST_DIR}/plot-powers.o")
    run_command("${DISCLD}" "${TEST_DIR}/plot-powers.o" ${link} -o "${TEST_DIR}/plot-powers.bin")
    run_command("${GSU_RUNNER}" "${TEST_DIR}/plot-powers.bin" 0x706000 --ram-byte 0x700100 249 --ram-byte 0x700101 255
        --word 0x700102 0 --word 0x700104 65529 --word 0x700106 17 --word 0x700108 23 --register 0 42 --register 6 0)
endforeach()
