# Each case has a private TEST_DIR supplied by the shared CTest/direct registry.
set(project_dir "${TEST_DIR}/a project")
file(MAKE_DIRECTORY "${project_dir}" "${TEST_DIR}/manual")
file(WRITE "${project_dir}/math.dci" "module math;\nword add(word left, word right);\n")
file(WRITE "${project_dir}/main.dc" "import \"math.dci\";\nvoid main() { word* output = (word*)0x100; *output = add(46, 103); }\n")
file(WRITE "${project_dir}/math.dc" "import \"math.dci\";\nword add(word left, word right) { return left + right; }\n")
set(manifest "[project]\nname = 'multifile'\ntarget = 'superfx'\nsources = [\n 'main.dc', # order is significant\n 'math.dc',\n]\n[target.superfx]\nmemory_mapping = 'lorom'\nexecution_memory = 'ram'\norigin = 0x70_0900\nram_bank = 0\nstack_pointer = 0x2000\n[runtime]\ninitialize = true\nentry = 'main'\n[output]\ndirectory = 'build'\nbinary = 'multifile.bin'\nassembly = 'final.s'\n")
file(WRITE "${project_dir}/discoc.toml" "${manifest}")

function(run_from directory)
    execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${directory}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Project command failed (${result}): ${ARGN}\n${output}\n${error}")
    endif()
endfunction()
function(equal_bytes left right)
    file(SHA256 "${left}" left_hash)
    file(SHA256 "${right}" right_hash)
    if(NOT left_hash STREQUAL right_hash)
        message(FATAL_ERROR "Files differ: ${left} and ${right}")
    endif()
endfunction()
function(project_failure pattern)
    execute_process(COMMAND "${DISCC}" ${ARGN} WORKING_DIRECTORY "${TEST_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result STREQUAL "0" OR NOT "${output}\n${error}" MATCHES "${pattern}")
        message(FATAL_ERROR "Expected project failure '${pattern}': ${ARGN}\n${output}\n${error}")
    endif()
    if("${output}\n${error}" MATCHES "Internal Compiler Error")
        message(FATAL_ERROR "Malformed manifest/source caused an internal compiler error")
    endif()
endfunction()
function(reject_manifest contents pattern)
    file(WRITE "${project_dir}/bad.toml" "${contents}")
    project_failure("${pattern}" build --config "${project_dir}/bad.toml")
endfunction()

if(CASE STREQUAL "project_build")
    run_from("${TEST_DIR}" "${DISCC}" build --help)
    run_from("${TEST_DIR}" "${DISCC}" --config "${project_dir}/discoc.toml" --help)
    run_from("${TEST_DIR}" "${DISCLD}" --config "${project_dir}/discoc.toml" --help)
    # Automatic discovery and --project work without locating discld on PATH.
    run_from("${project_dir}" "${DISCC}" build)
    # main STOP keeps its four-byte saved-entry frame, so R10 ends four bytes
    # below the configured initial pointer rather than unwinding to the host.
    run_command("${GSU_RUNNER}" "${project_dir}/build/multifile.bin" 0x700900
        --initial-sp 0x7770 --initial-ram-bank 1 --word 0x100 149 --register 10 0x1ffc --rambr 0 0)
    foreach(unit IN ITEMS main math)
        run_command("${DISCC}" "${project_dir}/${unit}.dc" --origin 0x700900 --execution-memory ram
            --memory-mapping lorom -o "${TEST_DIR}/manual/${unit}.o")
    endforeach()
    equal_bytes("${project_dir}/build/0-main.o" "${TEST_DIR}/manual/main.o")
    equal_bytes("${project_dir}/build/1-math.o" "${TEST_DIR}/manual/math.o")
    run_command("${DISCLD}" "${TEST_DIR}/manual/main.o" "${TEST_DIR}/manual/math.o"
        --origin 0x700900 --ram-bank 0 --stack-pointer 0x2000 --init-runtime
        --emit-asm "${TEST_DIR}/manual/final.s" -o "${TEST_DIR}/manual/multifile.bin")
    equal_bytes("${project_dir}/build/multifile.bin" "${TEST_DIR}/manual/multifile.bin")
    equal_bytes("${project_dir}/build/final.s" "${TEST_DIR}/manual/final.s")
    run_command("${DISCAS}" "${project_dir}/build/final.s" -o "${TEST_DIR}/manual/final.o")
    run_command("${DISCLD}" "${TEST_DIR}/manual/final.o" -o "${TEST_DIR}/manual/roundtrip.bin")
    equal_bytes("${project_dir}/build/multifile.bin" "${TEST_DIR}/manual/roundtrip.bin")
    run_from("${TEST_DIR}" "${DISCC}" --project "${project_dir}/discoc.toml")
    equal_bytes("${project_dir}/build/multifile.bin" "${TEST_DIR}/manual/multifile.bin")
    # Same basenames must not overwrite each other's object files.
    file(MAKE_DIRECTORY "${project_dir}/one" "${project_dir}/two")
    file(WRITE "${project_dir}/one/shared.dc" "word helper(); void main() { word* p=(word*)0x100; *p=helper(); }")
    file(WRITE "${project_dir}/two/shared.dc" "word helper() { return 149; }")
    file(WRITE "${project_dir}/names.toml" "[project]\nsources=['one/shared.dc', 'two/shared.dc']\n[runtime]\ninitialize=true\n[output]\ndirectory='names output'\n")
    run_from("${TEST_DIR}" "${DISCC}" build --config "${project_dir}/names.toml")
    if(NOT EXISTS "${project_dir}/names output/0-shared.o" OR NOT EXISTS "${project_dir}/names output/1-shared.o")
        message(FATAL_ERROR "Indexed project object names are missing")
    endif()
    run_command("${GSU_RUNNER}" "${project_dir}/names output/new.bin" 0x8000 --word 0x100 149)

elseif(CASE STREQUAL "project_configuration")
    foreach(order IN ITEMS before after)
        if(order STREQUAL "before")
            set(options --origin 0x701000 --config "${project_dir}/discoc.toml")
        else()
            set(options --config "${project_dir}/discoc.toml" --origin 0x701000)
        endif()
        run_from("${TEST_DIR}" "${DISCC}" build ${options} --ram-bank 1 --stack-pointer 0x3000
            --output-dir "override ${order}" -o "${TEST_DIR}/override ${order}/payload.bin"
            --emit-asm "${TEST_DIR}/override ${order}/linked.s")
        run_command("${GSU_RUNNER}" "${TEST_DIR}/override ${order}/payload.bin" 0x701000
            --word 0x710100 149 --register 10 0x2ffc --rambr 0 1)
        run_command("${DISCLD}" "${TEST_DIR}/override ${order}/0-main.o" "${TEST_DIR}/override ${order}/1-math.o"
            --origin 0x701000 --ram-bank 1 --stack-pointer 0x3000 --init-runtime
            --emit-asm "${TEST_DIR}/manual/${order}.s" -o "${TEST_DIR}/manual/${order}.bin")
        equal_bytes("${TEST_DIR}/override ${order}/payload.bin" "${TEST_DIR}/manual/${order}.bin")
        equal_bytes("${TEST_DIR}/override ${order}/linked.s" "${TEST_DIR}/manual/${order}.s")
    endforeach()
    equal_bytes("${TEST_DIR}/override before/payload.bin" "${TEST_DIR}/override after/payload.bin")
    run_from("${TEST_DIR}" "${DISCC}" build --config "${project_dir}/discoc.toml" --output-dir "directory only")
    if(NOT EXISTS "${TEST_DIR}/directory only/multifile.bin" OR NOT EXISTS "${TEST_DIR}/directory only/final.s")
        message(FATAL_ERROR "--output-dir must move manifest-named outputs as well as objects")
    endif()
    # All existing one-source and object-link invocations also accept defaults.
    run_command("${DISCC}" --config "${project_dir}/discoc.toml" "${project_dir}/main.dc" -o "${TEST_DIR}/manual/config.o")
    equal_bytes("${TEST_DIR}/manual/config.o" "${TEST_DIR}/directory only/0-main.o")
    run_command("${DISCC}" "${project_dir}/main.dc" --origin 0x701000 --config "${project_dir}/discoc.toml"
        -o "${TEST_DIR}/manual/override.o")
    equal_bytes("${TEST_DIR}/manual/override.o" "${TEST_DIR}/override before/0-main.o")
    run_command("${DISCLD}" "${TEST_DIR}/manual/config.o" "${TEST_DIR}/directory only/1-math.o"
        --config "${project_dir}/discoc.toml")
    equal_bytes("${project_dir}/build/multifile.bin" "${TEST_DIR}/directory only/multifile.bin")
    foreach(order IN ITEMS before after)
        if(order STREQUAL "before")
            set(options --origin 0x701000 --config "${project_dir}/discoc.toml")
        else()
            set(options --config "${project_dir}/discoc.toml" --origin 0x701000)
        endif()
        run_from("${TEST_DIR}" "${DISCLD}" "${TEST_DIR}/manual/config.o" "${TEST_DIR}/directory only/1-math.o"
            ${options} --ram-bank 1 --stack-pointer 0x3000 -o "link-${order}.bin" --no-emit-asm)
        equal_bytes("${TEST_DIR}/link-${order}.bin" "${TEST_DIR}/override before/payload.bin")
    endforeach()
    file(WRITE "${TEST_DIR}/no startup.s" "assembly sentinel")
    run_from("${TEST_DIR}" "${DISCC}" build --config "${project_dir}/discoc.toml"
        --no-init-runtime --emit-asm "${TEST_DIR}/no startup.s" --no-emit-asm -o "${TEST_DIR}/no startup.bin")
    run_command("${GSU_RUNNER}" "${TEST_DIR}/no startup.bin" 0x700900 --word 0x100 149 --register 10 0x1ffc)
    file(READ "${TEST_DIR}/no startup.s" sentinel)
    if(NOT sentinel STREQUAL "assembly sentinel")
        message(FATAL_ERROR "--no-emit-asm did not preserve the existing assembly file")
    endif()
    # Mutable globals require one explicit initialization contract.
    file(WRITE "${project_dir}/globals.dc" "word result = 7; void main(){ word* p=(word*)0x100; *p=result; }")
    file(WRITE "${project_dir}/globals.toml" "[project]\nsources=['globals.dc']\n[target.gsu]\nram_origin=0x600\n[runtime]\ninitialize=true\nhost_initialized_globals=false\n[output]\ndirectory='globals'\n")
    run_from("${TEST_DIR}" "${DISCC}" build --config "${project_dir}/globals.toml")
    run_command("${GSU_RUNNER}" "${project_dir}/globals/new.bin" 0x8000 --word 0x600 7 --word 0x100 7)
    run_from("${TEST_DIR}" "${DISCC}" build --config "${project_dir}/globals.toml"
        --no-init-runtime --host-initialized-globals -o "${TEST_DIR}/host.bin")
    run_command("${GSU_RUNNER}" "${TEST_DIR}/host.bin" 0x8000 --ram-byte 0x700600 7 --word 0x100 7)
    string(REPLACE "initialize=true\nhost_initialized_globals=false" "initialize=false\nhost_initialized_globals=true" host_manifest
        "[project]\nsources=['globals.dc']\n[target.gsu]\nram_origin=0x600\n[runtime]\ninitialize=true\nhost_initialized_globals=false\n[output]\ndirectory='globals'\n")
    file(WRITE "${project_dir}/host.toml" "${host_manifest}")
    run_from("${TEST_DIR}" "${DISCC}" build --config "${project_dir}/host.toml" --init-runtime --no-host-initialized-globals
        -o "${TEST_DIR}/runtime.bin")
    run_command("${GSU_RUNNER}" "${TEST_DIR}/runtime.bin" 0x8000 --word 0x100 7)

elseif(CASE STREQUAL "project_diagnostics")
    run_from("${project_dir}" "${DISCC}" build)
    file(SHA256 "${project_dir}/build/multifile.bin" original_binary)
    file(SHA256 "${project_dir}/discoc.toml" original_manifest)
    file(SHA256 "${project_dir}/main.dc" original_source)
    file(SHA256 "${project_dir}/math.dci" original_interface)
    project_failure("overwrite the manifest" build --config "${project_dir}/discoc.toml" -o "${project_dir}/./discoc.toml")
    project_failure("overwrite a project source" build --config "${project_dir}/discoc.toml" --emit-asm "${project_dir}/main.dc")
    project_failure("overwrite a source/interface" build --config "${project_dir}/discoc.toml" -o "${project_dir}/math.dci")
    file(CREATE_LINK "${project_dir}/main.dc" "${project_dir}/source-alias.bin" RESULT alias_status)
    if(NOT alias_status STREQUAL "0")
        message(FATAL_ERROR "Cannot create hard-link alias regression fixture: ${alias_status}")
    endif()
    project_failure("overwrite a project source" build --config "${project_dir}/discoc.toml" -o "${project_dir}/source-alias.bin")
    run_expected_failure_contains("overwrite an input source/interface" "${DISCC}" "${project_dir}/main.dc" -o "${project_dir}/math.dci")
    project_failure("output paths must be different" build --config "${project_dir}/discoc.toml"
        -o "${project_dir}/build/0-main.o")
    project_failure("Only one project manifest" build --config "${project_dir}/discoc.toml" --config "${project_dir}/discoc.toml")
    project_failure("requires a value" build --origin)
    project_failure("requires a value" --project)
    project_failure("Unknown project-build option" build --config "${project_dir}/discoc.toml" --optimize 2)
    project_failure("Cannot open manifest" build --config "${project_dir}/missing.toml")
    run_expected_failure_contains("Only one --config" "${DISCLD}" --config "${project_dir}/discoc.toml" --config "${project_dir}/discoc.toml")
    run_expected_failure_contains("requires a filename" "${DISCC}" --config)
    run_expected_failure_contains("overwrite the manifest" "${DISCLD}"
        "${project_dir}/build/0-main.o" "${project_dir}/build/1-math.o"
        --config "${project_dir}/discoc.toml" -o "${project_dir}/discoc.toml")
    # A filename resembling an option must still be consumed as a value.
    run_from("${TEST_DIR}" "${DISCLD}" "${project_dir}/build/0-main.o" "${project_dir}/build/1-math.o"
        --config "${project_dir}/discoc.toml" -o --target --no-emit-asm)
    if(NOT EXISTS "${TEST_DIR}/--target")
        message(FATAL_ERROR "Flag-looking filename was reinterpreted as a target option")
    endif()
    foreach(pair IN ITEMS manifest source interface)
        if(pair STREQUAL "manifest")
            set(path "discoc.toml")
        elseif(pair STREQUAL "source")
            set(path "main.dc")
        else()
            set(path "math.dci")
        endif()
        file(SHA256 "${project_dir}/${path}" current_hash)
        if(NOT current_hash STREQUAL original_${pair})
            message(FATAL_ERROR "Project validation overwrote ${pair}")
        endif()
    endforeach()
    reject_manifest("[project]\nsources=['main.dc','./main.dc']" "Duplicate project source")
    reject_manifest("[project]\nsources=[]" "nonempty project.sources")
    reject_manifest("[project]\nsources=['math.dci']" "must be .dc implementations")
    reject_manifest("[project]\nsources=['missing.dc']" "Cannot open module")
    reject_manifest("[project]\nsources=['main.dc'" "Expected ','")
    reject_manifest("[project]\nsources=['main.dc']\n[output]\nwrong='x'" "Unknown or unsupported")
    reject_manifest("[project]\nsources=['main.dc']\n[target.gsu]\nram_bank=2" "out of range")
    reject_manifest("${manifest}\n[runtime]" "Duplicate table")
    string(REPEAT "# bounded input\n" 5000 oversized)
    reject_manifest("${oversized}" "exceeds 64 KiB")
    project_failure("Origin does not match" build --config "${project_dir}/discoc.toml" --origin 0x8000)
    project_failure("Initial stack pointer must be even" build --config "${project_dir}/discoc.toml" --stack-pointer 0x2001)
    project_failure("Static RAM origin must be word-aligned" build --config "${project_dir}/discoc.toml" --ram-origin 0x401)
    project_failure("Runtime options require" build --config "${project_dir}/discoc.toml" --no-init-runtime --entry main)
    project_failure("crosses a program-bank boundary" build --config "${project_dir}/discoc.toml" --origin 0x70fff0)
    # A valid but incomplete object set must not replace the previous payload.
    file(WRITE "${project_dir}/math.dc" "word other(){ return 1; }")
    project_failure("Unresolved symbol|Undefined symbol" build --config "${project_dir}/discoc.toml")
    file(WRITE "${project_dir}/math.dc" "word add(word a, word b) { return missing; }")
    project_failure("Use of undeclared symbol 'missing'" build --config "${project_dir}/discoc.toml")
    file(SHA256 "${project_dir}/build/multifile.bin" after_failures)
    if(NOT original_binary STREQUAL after_failures)
        message(FATAL_ERROR "Failed project build replaced a previously linked binary")
    endif()

elseif(CASE STREQUAL "project_targets")
    file(WRITE "${project_dir}/spc.toml" "[project]\ntarget='spc700'\nsources=['main.dc','math.dc']\n[target.spc700]\norigin=0x0200\n[output]\ndirectory='spc-build'\n")
    run_from("${TEST_DIR}" "${DISCC}" build --config "${project_dir}/spc.toml" --check)
    if(EXISTS "${project_dir}/spc-build")
        message(FATAL_ERROR "Frontend-only project checks created output directories")
    endif()
    project_failure("no code-generation backend" build --config "${project_dir}/spc.toml")
    if(EXISTS "${project_dir}/spc-build")
        message(FATAL_ERROR "Unavailable SPC backend wrote project outputs")
    endif()
    run_from("${TEST_DIR}" "${DISCC}" build --config "${project_dir}/spc.toml" --target gsu --init-runtime)
    run_command("${GSU_RUNNER}" "${project_dir}/spc-build/new.bin" 0x8000 --word 0x100 149)
    run_expected_failure_contains("target does not match input objects" "${DISCLD}"
        "${project_dir}/spc-build/0-main.o" "${project_dir}/spc-build/1-math.o"
        --config "${project_dir}/spc.toml")
    file(WRITE "${project_dir}/hirom.toml" "[project]\nsources=['main.dc','math.dc']\n[target.gsu]\nmemory_mapping='hirom'\nexecution_memory='rom'\norigin=0x408000\n[runtime]\ninitialize=true\n[output]\ndirectory='hirom'\n")
    run_from("${TEST_DIR}" "${DISCC}" build --config "${project_dir}/hirom.toml")
    run_command("${GSU_RUNNER}" "${project_dir}/hirom/new.bin" 0x408000 --word 0x100 149)
    run_expected_failure_contains("mapping does not match input objects" "${DISCLD}"
        "${project_dir}/spc-build/0-main.o" "${project_dir}/spc-build/1-math.o"
        --config "${project_dir}/hirom.toml")
    run_from("${project_dir}" "${DISCC}" build --check)
    if(EXISTS "${project_dir}/build")
        message(FATAL_ERROR "GSU frontend-only check wrote outputs")
    endif()
else()
    message(FATAL_ERROR "Unknown project regression: ${CASE}")
endif()
