# Isolated fixtures exercise source imports through the public CLI and linker.
set(project_dir "${TEST_DIR}/source project")
file(MAKE_DIRECTORY "${project_dir}/src" "${project_dir}/modules" "${TEST_DIR}/manual")
foreach(name IN ITEMS discoc.toml src/main.dc modules/types.dc modules/math.dc modules/graphics.dc)
    configure_file("${ROOT_DIR}/examples/source_imports/${name}" "${project_dir}/${name}" COPYONLY)
endforeach()

function(module_command)
    execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${TEST_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Module command failed (${result}): ${ARGV}\n${output}\n${error}")
    endif()
    set(module_output "${output}" PARENT_SCOPE)
endfunction()
function(module_failure pattern)
    execute_process(COMMAND "${DISCC}" ${ARGN} WORKING_DIRECTORY "${TEST_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
    if(result STREQUAL "0" OR NOT "${output}\n${error}" MATCHES "${pattern}" OR
       "${output}\n${error}" MATCHES "Internal Compiler Error|IR verifier:")
        message(FATAL_ERROR "Expected language/module diagnostic '${pattern}': ${ARGN}\n${output}\n${error}")
    endif()
endfunction()
function(module_equal left right)
    file(SHA256 "${left}" left_hash)
    file(SHA256 "${right}" right_hash)
    if(NOT left_hash STREQUAL right_hash)
        message(FATAL_ERROR "Module output mismatch: ${left} and ${right}")
    endif()
endfunction()
function(check_module_example binary)
    run_command("${GSU_RUNNER}" "${binary}" 0x8000 --word 0x100 149 --word 0x102 8
        --word 0x104 4 --word 0x106 6 --word 0x108 2 --word 0x10a 6 --register 10 0x1ffc)
endfunction()

if(CASE STREQUAL "module_imports")
    module_command("${DISCC}" build --config "${project_dir}/discoc.toml")
    string(REGEX MATCHALL "Successfully generated" generated "${module_output}")
    list(LENGTH generated generation_count)
    file(GLOB objects "${project_dir}/build/*.o")
    list(LENGTH objects object_count)
    if(NOT generation_count EQUAL 4 OR NOT object_count EQUAL 4)
        message(FATAL_ERROR "Diamond dependencies must compile once each: ${module_output}")
    endif()
    set(binary "${project_dir}/build/source-imports.bin")
    check_module_example("${binary}")
    # The importing unit contains main, not the imported function definitions.
    module_command("${DISCC}" --config "${project_dir}/discoc.toml" --emit-ir "${project_dir}/src/main.dc")
    string(REGEX MATCHALL "function [a-z_]+\\(\\)" functions "${module_output}")
    if(NOT functions STREQUAL "function main()")
        message(FATAL_ERROR "Source imports pasted implementation bodies into root IR: ${module_output}")
    endif()
    set(direct_objects "")
    set(assembly_objects "")
    foreach(pair IN ITEMS "0|src/main" "1|modules/types" "2|modules/math" "3|modules/graphics")
        string(REPLACE "|" ";" fields "${pair}")
        list(GET fields 0 index)
        list(GET fields 1 source)
        get_filename_component(name "${source}" NAME)
        module_command("${DISCC}" --config "${project_dir}/discoc.toml" "${project_dir}/${source}.dc"
            -o "${TEST_DIR}/manual/${name}.o")
        module_equal("${project_dir}/build/${index}-${name}.o" "${TEST_DIR}/manual/${name}.o")
        module_command("${DISCC}" --config "${project_dir}/discoc.toml" --emit-asm "${project_dir}/${source}.dc"
            -o "${TEST_DIR}/manual/${name}.s")
        run_command("${DISCAS}" "${TEST_DIR}/manual/${name}.s" -o "${TEST_DIR}/manual/${name}-asm.o")
        list(APPEND direct_objects "${TEST_DIR}/manual/${name}.o")
        list(APPEND assembly_objects "${TEST_DIR}/manual/${name}-asm.o")
    endforeach()
    foreach(backend IN ITEMS direct assembly)
        run_command("${DISCLD}" ${${backend}_objects} --init-runtime --ram-origin 0x600 -o "${TEST_DIR}/${backend}.bin")
        module_equal("${binary}" "${TEST_DIR}/${backend}.bin")
        check_module_example("${TEST_DIR}/${backend}.bin")
    endforeach()
    run_command("${DISCAS}" "${project_dir}/build/source-imports.s" -o "${TEST_DIR}/final.o")
    run_command("${DISCLD}" "${TEST_DIR}/final.o" -o "${TEST_DIR}/final.bin")
    module_equal("${binary}" "${TEST_DIR}/final.bin")
    # An explicit source also reached through imports must not be compiled twice.
    file(READ "${project_dir}/discoc.toml" manifest)
    string(REPLACE "sources = [\"src/main.dc\"]" "sources = [\"src/main.dc\", \"modules/math.dc\"]" explicit "${manifest}")
    file(WRITE "${project_dir}/explicit.toml" "${explicit}")
    module_command("${DISCC}" build --config "${project_dir}/explicit.toml" --output-dir "explicit")
    string(REGEX MATCHALL "Successfully generated" generated "${module_output}")
    list(LENGTH generated generation_count)
    if(NOT generation_count EQUAL 4 OR NOT EXISTS "${TEST_DIR}/explicit/0-main.o" OR NOT EXISTS "${TEST_DIR}/explicit/1-math.o")
        message(FATAL_ERROR "Explicit roots lost link order or duplicated an imported source")
    endif()
    check_module_example("${TEST_DIR}/explicit/source-imports.bin")
    # Frontend checks discover the same graph but neither generate nor link.
    foreach(target IN ITEMS gsu spc700)
        module_command("${DISCC}" build --config "${project_dir}/discoc.toml" --target "${target}"
            --check --output-dir "check-${target}")
        if(EXISTS "${TEST_DIR}/check-${target}")
            message(FATAL_ERROR "Source-import --check created output directories")
        endif()
    endforeach()
    # .dci remains interface-only and does not automatically imply a .dc file.
    file(WRITE "${project_dir}/interface.dci" "module Interface; constexpr internal word PRIVATE_N=2; constexpr word N=PRIVATE_N+1; word external();\n")
    file(WRITE "${project_dir}/interface.dc" "word external(){return 149;}\n")
    file(WRITE "${project_dir}/interface-main.dc" "import \"interface.dci\"; static_assert(N == 3); void main(){external();}\n")
    module_command("${DISCC}" --check "${project_dir}/interface-main.dc")
    module_command("${DISCC}" "${project_dir}/interface-main.dc" -o "${TEST_DIR}/interface-main.o")
    run_expected_failure_contains("Undefined symbol" "${DISCLD}" "${TEST_DIR}/interface-main.o" -o "${TEST_DIR}/missing-implementation.bin")
    file(WRITE "${project_dir}/interface.dc" "import \"interface.dci\"; word external(){return 149;}\n")
    file(WRITE "${project_dir}/source-and-interface.dc" "import \"interface.dc\"; static_assert(N == 3); void main(){word* out=(word*)0x100; *out=external();}\n")
    file(WRITE "${project_dir}/compatible.toml" "[project]\nsources=['source-and-interface.dc']\n[runtime]\ninitialize=true\n[output]\ndirectory='compatible'\n")
    module_command("${DISCC}" build --config "${project_dir}/compatible.toml")
    run_command("${GSU_RUNNER}" "${project_dir}/compatible/new.bin" 0x8000 --word 0x100 149)
    # Fixed RAM origins/runtime settings propagate to automatically compiled
    # sources exactly as they do in the documented individual-tool workflow.
    file(WRITE "${project_dir}/ram-main.dc" "import \"ram-math.dc\"; void main(){volatile word* out=(volatile word*)0x100; *out=add(30,12);}\n")
    file(WRITE "${project_dir}/ram-math.dc" "word add(word a,word b){return a+b;}\n")
    file(WRITE "${project_dir}/ram.toml" "[project]\nsources=['ram-main.dc']\n[target.gsu]\norigin=0x700900\nexecution_memory='ram'\n[runtime]\ninitialize=true\n[output]\ndirectory='ram output'\n")
    module_command("${DISCC}" build --config "${project_dir}/ram.toml")
    run_command("${GSU_RUNNER}" "${project_dir}/ram output/new.bin" 0x700900 --initial-sp 0x7770
        --initial-ram-bank 1 --word 0x100 42 --rambr 0 0 --register 10 0x1ffc)

elseif(CASE STREQUAL "module_import_paths")
    set(search "${TEST_DIR}/search project")
    file(MAKE_DIRECTORY "${search}/src" "${search}/first" "${search}/second" "${TEST_DIR}/override")
    file(WRITE "${search}/src/main.dc" "import \"library.dc\"; static_assert(VALUE == 1); void main(){}\n")
    file(WRITE "${search}/first/library.dc" "constexpr word VALUE=1;\n")
    file(WRITE "${search}/second/library.dc" "constexpr word VALUE=2;\n")
    file(WRITE "${TEST_DIR}/override/library.dc" "constexpr word VALUE=3;\n")
    file(WRITE "${search}/discoc.toml" "[project]\nsources=['src/main.dc']\n[compiler]\nimport_paths=['first','second']\n")
    module_command("${DISCC}" build --check --config "${search}/discoc.toml")
    module_command("${DISCC}" --check --config "${search}/discoc.toml" "${search}/src/main.dc")
    # Local file wins even over the first configured search directory.
    file(WRITE "${search}/src/library.dc" "constexpr word VALUE=4;\n")
    file(WRITE "${search}/src/main.dc" "import \"library.dc\"; static_assert(VALUE == 4); void main(){}\n")
    module_command("${DISCC}" build --check --config "${search}/discoc.toml")
    file(WRITE "${search}/src/library.dc" "void broken(\n")
    module_failure("src/library.dc:.*Expect type" build --check --config "${search}/discoc.toml")
    file(REMOVE "${search}/src/library.dc")
    file(WRITE "${search}/src/main.dc" "import \"library.dc\"; static_assert(VALUE == 3); void main(){}\n")
    foreach(flags IN ITEMS "--import-path" "-I" "attached")
        if(flags STREQUAL "attached")
            set(options "-Ioverride")
        else()
            set(options "${flags}" override)
        endif()
        module_command("${DISCC}" --check ${options} --config "${search}/discoc.toml" "${search}/src/main.dc")
        module_command("${DISCC}" build --check --config "${search}/discoc.toml" ${options})
    endforeach()
    # CLI replaces, rather than silently retaining, the manifest search list.
    file(WRITE "${search}/first/only-configured.dc" "constexpr word CONFIG_ONLY=1;\n")
    file(WRITE "${search}/src/main.dc" "import \"only-configured.dc\"; void main(){}\n")
    module_failure("Cannot open module.*only-configured.dc" build --check --config "${search}/discoc.toml" --import-path override)
    module_command("${DISCC}" build --check --config "${search}/discoc.toml")
    file(WRITE "${search}/src/main.dc" "import \"library.dc\"; static_assert(VALUE == 2); void main(){}\n")
    module_command("${DISCC}" --check --import-path "${search}/second" --import-path "${search}/first" "${search}/src/main.dc")
    # Search paths work for .dci and transitive imports as well as sources.
    file(WRITE "${search}/second/public.dci" "module Public; import \"library.dc\"; constexpr word DOUBLE=VALUE*2;\n")
    file(WRITE "${search}/src/main.dc" "import \"public.dci\"; static_assert(DOUBLE == 4); void main(){}\n")
    module_command("${DISCC}" --check -I "${search}/second" "${search}/src/main.dc")
    module_failure("requires a value" --check "${search}/src/main.dc" --import-path)
    module_failure("requires a value" build --config "${search}/discoc.toml" -I)

elseif(CASE STREQUAL "module_import_diagnostics")
    file(WRITE "${project_dir}/private.dc" "internal word hidden(){return 1;} constexpr internal word SECRET=2; internal word state=3;\n")
    foreach(name IN ITEMS hidden SECRET state)
        file(WRITE "${project_dir}/bad.dc" "import \"private.dc\"; void main(){${name};}\n")
        if(name STREQUAL "hidden")
            file(WRITE "${project_dir}/bad.dc" "import \"private.dc\"; void main(){hidden();}\n")
        endif()
        module_failure("(undeclared|Undefined|Unknown).*${name}" --check "${project_dir}/bad.dc")
    endforeach()
    file(WRITE "${project_dir}/bad.dc" "void main(){import \"private.dc\";}\n")
    module_failure("Expect expression|file scope|Imports" --check "${project_dir}/bad.dc")
    file(WRITE "${project_dir}/bad.dc" "void main(){} import \"private.dc\";\n")
    module_failure("Imports must precede declarations" --check "${project_dir}/bad.dc")
    file(WRITE "${project_dir}/bad.dc" "@import \"private.dc\";\n")
    module_failure("Expect attribute name" --check "${project_dir}/bad.dc")
    foreach(path IN ITEMS "missing.dc" "wrong.txt" "/absolute.dc" "C:/absolute.dc")
        file(WRITE "${project_dir}/bad.dc" "import \"${path}\";\n")
        module_failure("Cannot open module|Imports require" --check "${project_dir}/bad.dc")
    endforeach()
    file(WRITE "${project_dir}/bad.dc" "import \"a.dc\";\n")
    file(WRITE "${project_dir}/a.dc" "import \"b.dc\";\n")
    file(WRITE "${project_dir}/b.dc" "import \"./a.dc\";\n")
    module_failure("b.dc:1:.*Cyclic module import:.*a.dc.*b.dc.*a.dc" --check "${project_dir}/bad.dc")
    file(WRITE "${project_dir}/bad.dc" "@cfg(spc700) import \"absent.dc\"; void main(){}\n")
    module_command("${DISCC}" --check --target gsu "${project_dir}/bad.dc")
    module_failure("Cannot open module" --check --target spc700 "${project_dir}/bad.dc")
    file(WRITE "${project_dir}/bad.dc" "import \"private.dc\"; import \"private.dc\"; void main(){}\n")
    module_command("${DISCC}" --check "${project_dir}/bad.dc")
    # A semantic failure inside an imported implementation is not hidden by
    # projecting only its function prototype; it prevents a stale binary link.
    module_command("${DISCC}" build --config "${project_dir}/discoc.toml")
    file(SHA256 "${project_dir}/build/source-imports.bin" old_binary)
    file(SHA256 "${project_dir}/modules/types.dc" old_source)
    module_failure("overwrite a source/interface" build --config "${project_dir}/discoc.toml" -o "${project_dir}/modules/types.dc")
    module_failure("overwrite an input source/interface" "${project_dir}/src/main.dc" --config "${project_dir}/discoc.toml"
        -o "${project_dir}/modules/types.dc")
    file(SHA256 "${project_dir}/modules/types.dc" protected_source)
    if(NOT protected_source STREQUAL old_source)
        message(FATAL_ERROR "An auto-discovered source was overwritten")
    endif()
    file(WRITE "${project_dir}/modules/math.dc" "import \"types.dc\"; word add(word a,word b){return missing;}\n")
    module_failure("math.dc:.*undeclared symbol.*missing" build --config "${project_dir}/discoc.toml")
    module_failure("math.dc:.*undeclared symbol.*missing" --check --config "${project_dir}/discoc.toml" "${project_dir}/src/main.dc")
    file(SHA256 "${project_dir}/build/source-imports.bin" after_failure)
    if(NOT after_failure STREQUAL old_binary)
        message(FATAL_ERROR "Failed imported source changed an existing linked binary")
    endif()
    # Name conflicts must not depend on which import happened to load first.
    file(WRITE "${project_dir}/left.dc" "type Count=word;\n")
    file(WRITE "${project_dir}/right.dc" "type Count=byte;\n")
    file(WRITE "${project_dir}/bad.dc" "import \"left.dc\"; import \"right.dc\"; void main(){}\n")
    module_failure("Conflicting type alias" --check "${project_dir}/bad.dc")
else()
    message(FATAL_ERROR "Unknown source-module case: ${CASE}")
endif()
