string(REGEX REPLACE "^language_conformance_" "" category "${CASE}")
file(GLOB sources "${ROOT_DIR}/tests/language/${category}/*.dc")
list(SORT sources)
if(NOT sources)
    message(FATAL_ERROR "Empty conformance category: ${category}")
endif()
foreach(source IN LISTS sources)
    file(READ "${source}" content)
    get_filename_component(case_name "${source}" NAME_WE)
    set(expected "")
    if(content MATCHES "// error: ([^\n]+)")
        set(expected "${CMAKE_MATCH_1}")
    endif()
    if(case_name MATCHES "^invalid" AND NOT expected)
        message(FATAL_ERROR "Negative conformance case is missing '// error: regex': ${source}")
    elseif(NOT case_name MATCHES "^(valid|invalid)")
        message(FATAL_ERROR "Conformance root cases must be named valid*.dc or invalid*.dc; put dependency fixtures in a subdirectory: ${source}")
    elseif(case_name MATCHES "^valid" AND expected)
        message(FATAL_ERROR "Positive conformance case cannot carry an error expectation: ${source}")
    endif()
    foreach(target IN ITEMS gsu spc700)
        if(content MATCHES "// target: gsu" AND target STREQUAL "spc700")
            continue()
        endif()
        set(diagnostic "${expected}")
        if(target STREQUAL "spc700" AND content MATCHES "// spc-error: ([^\n]+)")
            set(diagnostic "${CMAKE_MATCH_1}")
        endif()
        execute_process(COMMAND "${DISCC}" --check --target "${target}" "${source}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 15)
        # A timeout, signal or Windows exception is never a successful rejection.
        # User-facing diagnostics use EXIT_FAILURE (1), not an arbitrary exit.
        if(NOT result STREQUAL "0" AND NOT result STREQUAL "1")
            message(FATAL_ERROR "Compiler crashed or timed out (${target}, ${result}): ${source}\n${output}\n${error}")
        endif()
        if(diagnostic)
            if(NOT result STREQUAL "1" OR NOT error MATCHES ":[0-9]+:[0-9]+: error:" OR
               NOT error MATCHES "${diagnostic}" OR error MATCHES "IR verifier:")
                message(FATAL_ERROR "Invalid conformance input did not produce its language diagnostic (${target}): ${source}\n${output}\n${error}")
            endif()
        elseif(NOT result STREQUAL "0")
            message(FATAL_ERROR "Valid conformance input failed (${target}): ${source}\n${output}\n${error}")
        endif()
    endforeach()
endforeach()
