#pragma once

enum class TokenType {
    // Keywords
    KEYWORD_SWITCH,
    KEYWORD_CASE,
    KEYWORD_DEFAULT,
    KEYWORD_BREAK,
    KEYWORD_FAR,
    KEYWORD_SET,
    KEYWORD_STRUCT,
    KEYWORD_CONST,
    KEYWORD_VOLATILE,
    KEYWORD_RAM,
    KEYWORD_BOOL,
    KEYWORD_TRUE,
    KEYWORD_FALSE,
    KEYWORD_INTERNAL,
    KEYWORD_EXPORT,
    KEYWORD_EXTERN,
    KEYWORD_ROM,
    KEYWORD_DRAW,
    KEYWORD_AT,
    KEYWORD_WITH,
    KEYWORD_COLOR,
    KEYWORD_SET_PLOT_OPTIONS,
    KEYWORD_FLUSH_PIXELS,
    KEYWORD_SET_COLOR,
    KEYWORD_PLOT_BEGIN,
    KEYWORD_PLOT_END,
    KEYWORD_PLOT,
    KEYWORD_UNSIGNED,
    KEYWORD_FOR,
    KEYWORD_WHILE,
    KEYWORD_IF,
    KEYWORD_ELSE,
    KEYWORD_WORD,
    KEYWORD_BYTE,
    KEYWORD_VOID,
    KEYWORD_RETURN,
    KEYWORD_CACHE,
    AT_SIGN,
    KEYWORD_CONSTEXPR, KEYWORD_ENUM,
    KEYWORD_SIZEOF, KEYWORD_ALIGNOF, KEYWORD_OFFSETOF, KEYWORD_STATIC_ASSERT,
    KEYWORD_NULL, KEYWORD_CONTINUE, KEYWORD_FALLTHROUGH,
    KEYWORD_MODULE, KEYWORD_IMPORT, KEYWORD_TYPE,
    ARROW, PLUS_PLUS, MINUS_MINUS,
    PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, SLASH_EQUAL, PERCENT_EQUAL,
    AND_EQUAL, OR_EQUAL, XOR_EQUAL, SHIFT_LEFT_EQUAL, SHIFT_RIGHT_EQUAL,

    // Single-character tokens
    LPAREN, RPAREN, LBRACE, RBRACE, SEMICOLON,
    COLON,
    EQUAL,
    LBRACKET, RBRACKET,
    AMPERSAND,
    COMMA,
    DOT,

    // Operators
    PLUS, MINUS, STAR, SLASH, // For + - * /
    PERCENT, PIPE, CARET, TILDE, SHIFT_LEFT, SHIFT_RIGHT,
    AND_AND, OR_OR, BANG,

    // Comparison Operators
    GREATER,         // >
    GREATER_EQUAL,   // >=
    LESS,            // <
    LESS_EQUAL,      // <=
    EQUAL_EQUAL,     // ==
    BANG_EQUAL,      // !=

    // Literals and Identifiers
    LITERAL_INTEGER,
    LITERAL_STRING, LITERAL_CHARACTER,
    IDENTIFIER,

    // Special tokens
    END_OF_FILE,
    UNKNOWN
};
