# Keep the direct compiler scripts and CMake on the same source manifest.
file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/build-sources.txt" source_groups)
foreach(line IN LISTS source_groups)
    if(line MATCHES "^#" OR line STREQUAL "")
        continue()
    endif()
    separate_arguments(fields UNIX_COMMAND "${line}")
    list(POP_FRONT fields group)
    set(resolved)
    foreach(field IN LISTS fields)
        if(field MATCHES "^@(.+)$")
            set(dependency "${CMAKE_MATCH_1}")
            if(NOT DEFINED DISCO_SOURCES_${dependency})
                message(FATAL_ERROR "Unknown source group: ${dependency}")
            endif()
            list(APPEND resolved ${DISCO_SOURCES_${dependency}})
        else()
            list(APPEND resolved "${field}")
        endif()
    endforeach()
    set(DISCO_SOURCES_${group} "${resolved}")
endforeach()
